### ISSUE TITLE
antsrnet to antspynet extract patches  discrepancy

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTsPyNet#14]
python  (fails in extract patches -  simple dimensionality issue )

```
import ants
import antspynet
image = ants.image_read(ants.get_ants_data('r16'))
image = ants.merge_channels( (image, image,image) )
image_patches = antspynet.extract_image_patches(
        image,
        patch_size=image.shape,
        max_number_of_patches=1,
        stride_length=image.shape,
        return_as_array=True )

```

gives

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/stnava/.pyenv/versions/3.8.1/lib/python3.8/site-packages/antspynet-0.0-py3.8.egg/antspynet/utilities/super_resolution_utilities.py", line 302, in apply_super_resolution_model_to_image
    image_patches = extract_image_patches(
  File "/Users/stnava/.pyenv/versions/3.8.1/lib/python3.8/site-packages/antspynet-0.0-py3.8.egg/antspynet/utilities/extract_image_patches.py", line 236, in extract_image_patches
    patch_array[i, :, :, :] = patch
ValueError: could not broadcast input array from shape (256,3,256) into shape (256,256,3)
```

in ANTsR, we get

```
library(ANTsR)
library(ANTsRNet)
image = ri(1)
mimg =  mergeChannels( list(image,image,image))
tt=extractImagePatches( mimg, patchSize=dim(mimg), maxNumberOfPatches=1, strideLength=dim(mimg), returnAsArray=T)

```

**Comment by ntustison** [comment]
Thanks @stnava .  I'll take a look at that in a little bit.

**Comment by ntustison** [comment]
Again, thanks @stnava --- was just reminded of something.  It's currently [fixed](https://github.com/ANTsX/ANTsPyNet/commit/5f64287e693ff15b3588233b13eb065307a846e2), I think.  

So this is what was causing the problem:

```
# ANTsR 
> dim( as.array( image ) )
[1]   3 256 256

# ANTsPy
>>> (image.numpy()).shape
(256, 256, 3)
```
