### ISSUE TITLE
Resampling Utilities Example

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTsPyNet#15]
![xray](https://user-images.githubusercontent.com/324222/99847457-1847dd00-2b46-11eb-9b1b-f5f19e0601ea.jpg)

just wondering how this should work on the above image.

try 1:

```
import ants
img = ants.image_read("xray.jpg").split_channels()
for k in range(3):
    img[k] = ants.crop_indices( img[k], (0,0),(1926,2204) ) # dyadic

import antspynet
import tensorflow as tf
import keras as k
# set up the resampling using tf
input = k.Input( img[0].numpy().shape )
outdim = ( 1926/2, 2204/2 )
up = antspynet.ResampleTensorLayer2D( outdim, 'linear', name='xxx' )(input)

```

any working examples around?

**Comment by ntustison** [comment]
[This](https://github.com/ANTsXNet/TestingScripts/blob/master/testResampleTensorLayer.py) worked just a couple months ago.  Let me know if it doesn't.

**Comment by stnava** [comment]
same issue --- followed your example exactly.

```
>>> output = antspynet.ResampleTensorLayer2D(shape, types[i])(ft)
Traceback (most recent call last):
  File "/Users/stnava/.pyenv/versions/3.8.1/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2762, in __setattr__
    super(tracking.AutoTrackable, self).__setattr__(name, value)
AttributeError: can't set attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/stnava/.pyenv/versions/3.8.1/lib/python3.8/site-packages/antspynet-0.0-py3.8.egg/antspynet/utilities/resample_tensor_utilities.py", line 39, in __init__
    self.name = name
  File "/Users/stnava/.pyenv/versions/3.8.1/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2764, in __setattr__
    raise AttributeError(
AttributeError: Can't set the attribute "name", likely because it conflicts with an existing read-only @property of the object. Please choose a different name.
>>> 
>>> 
```


this is my environment:

```
absl-py==0.11.0
antspynet==0.0
antspyx==0.2.6
appdirs==1.4.3
astunparse==1.6.3
bleach==3.1.1
cachetools==4.1.1
certifi==2020.11.8
chardet==3.0.4
chart-studio==1.0.0
cloudpickle==1.4.1
colorama==0.4.3
cycler==0.10.0
decorator==4.4.2
distlib==0.3.0
dm-tree==0.1.5
docutils==0.15.2
fancycompleter==0.9.1
filelock==3.0.12
flatbuffers==1.12
gast==0.3.3
google-auth==1.23.0
google-auth-oauthlib==0.4.2
google-pasta==0.2.0
grpcio==1.33.2
h5py==2.10.0
idna==2.10
image-quality==1.2.5
imageio==2.8.0
jmespath==0.9.5
joblib==0.14.1
Keras==2.4.3
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
keyring==21.1.1
kiwisolver==1.3.1
libsvm==3.23.0.4
Markdown==3.3.3
matplotlib==3.3.3
networkx==2.4
nibabel==3.0.2
numpy==1.18.5
oauthlib==3.1.0
opencv-python==4.4.0.46
opt-einsum==3.3.0
pandas==1.0.1
patsy==0.5.1
pdbpp==0.10.2
Pillow==8.0.1
pkginfo==1.5.0.1
plotly==4.5.4
protobuf==3.14.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
Pygments==2.6.1
pyparsing==2.4.7
pyrepl==0.9.0
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.3.1
readme-renderer==24.0
requests==2.25.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
retrying==1.3.3
rsa==4.6
s3transfer==0.3.3
scikit-image==0.16.2
scikit-learn==0.22.2.post1
scipy==1.5.4
SimpleITK==1.2.4
six==1.15.0
sklearn==0.0
statsmodels==0.11.1
tb-nightly==2.4.0a20201112
tensorboard==2.4.0
tensorboard-plugin-wit==1.7.0
tensorflow==2.3.1
tensorflow-estimator==2.3.0
tensorflow-probability==0.11.1
termcolor==1.1.0
tf-estimator-nightly==2.4.0.dev2020102301
tqdm==4.43.0
twine==3.1.1
typing-extensions==3.7.4.3
urllib3==1.26.2
virtualenv==20.0.10
webcolors==1.11.1
webencodings==0.5.1
Werkzeug==1.0.1
wmctrl==0.3
wrapt==1.12.1
```

**Comment by ntustison** [comment]
Okay, let me see if I can fix it.

**Comment by ntustison** [comment]
By chance, does the R version work?

**Comment by stnava** [comment]
R works fine

```
tfResam2d <- function( img, outdim = losz, returnArray = FALSE, itype='nearestNeighbor', imdl ) {
  indim = dim( img )
  if ( missing( "imdl" ) ) {
    ft <- layer_input( c( indim, 1 ) )
    output <- layer_resample_tensor_2d( ft, outdim,  interpolationType = itype )
    km = keras_model( ft, output )
    return( km )
    }
  limg = predict( imdl, array( as.array( img ) , dim = c( 1, unlist( imdl$input_shape ) ) ) )
  if ( returnArray ) return( limg )
  limg = as.antsImage( limg[1,,,1] )
  antsCopyImageInfo( img, limg )
  antsSetSpacing( limg, antsGetSpacing( img ) * indim/outdim )
  limg
  }

rmdl=tfResam2d( ri(1), c(64,64))
 tfResam2d( ri(1), c(64,64),imdl=rmdl)

```

I have tf 2.4 in R

**Comment by ntustison** [comment]
Awesome.  Okay, I think I fixed the python version.  It was a tensorflow upgrade I missed.

**Comment by stnava** [comment]
does this work for you?

```
import ants
img = ants.image_read( ants.get_data("r16"))

import antspynet
import tensorflow as tf
import keras as k
# set up the resampling using tf
input = k.Input( img.numpy().shape )
outdim = ( 128,128 )
down = antspynet.ResampleTensorLayer2D( outdim, 'linear', name='xxx' )(input)
```

**Comment by stnava** [comment]
I get

```
Traceback (most recent call last):
  File "/Users/stnava/.pyenv/versions/3.8.1/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2829, in __setattr__
    super(tracking.AutoTrackable, self).__setattr__(name, value)
AttributeError: can't set attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/stnava/.pyenv/versions/3.8.1/lib/python3.8/site-packages/antspynet-0.0-py3.8.egg/antspynet/utilities/resample_tensor_utilities.py", line 39, in __init__
    self.name = name
  File "/Users/stnava/.pyenv/versions/3.8.1/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2831, in __setattr__
    raise AttributeError(
AttributeError: Can't set the attribute "name", likely because it conflicts with an existing read-only @property of the object. Please choose a different name.
```

**Comment by ntustison** [comment]
I had to modify it a bit (for the channel dim) but, otherwise, it works for me.

```
>>> import ants
>>> import numpy as np
>>> img = ants.image_read( ants.get_data("r16"))
>>> 
>>> import antspynet
>>> import tensorflow as tf
>>> import keras as k
>>> # set up the resampling using tf
>>> input = k.Input( np.expand_dims(img.numpy(), -1).shape )
>>> outdim = ( 128,128 )
>>> down = antspynet.ResampleTensorLayer2D( outdim, 'linear', name='xxx' )(input)
>>> down
<tf.Tensor 'resample_tensor_layer2d_4/resize/ResizeBilinear:0' shape=(None, 128, 128, 1) dtype=float32>
```

**Comment by stnava** [comment]
ok - made a pull request showing what works on my end

**Comment by ntustison** [comment]
Great that you got it to work.  So just go ahead and merge it whenever you want.  Heading out for a run pretty soon but let me know if you find anything else and I'll work on it when I get back.
