### ISSUE TITLE
Error while running regression_match_image utility on 2D RGB image 

### ISSUE THREAD

**Issue by ksindwan** [ANTsX/ANTsPyNet#18]
**sr_pred = antspynet.regression_match_image( sr_pred, ants.resample_image_to_target(img, sr_pred), poly_order=1)**

I am unable to run the regression_match_image function on the input image and output of the super resolution model.
Description of images 

img
ANTsImage
	 Pixel Type : float (float32)
	 Components : 3 (RGB)
	 Dimensions : (96, 96)
	 Spacing  : (0.254, 0.254)
	 Origin   : (0.0, 0.0)
	 Direction : [1. 0. 0. 1.]

sr_pred
ANTsImage
	 Pixel Type : float (float32)
	 Components : 3
	 Dimensions : (192, 192)
	 Spacing  : (0.127, 0.127)
	 Origin   : (0.0, 0.0)
	 Direction : [1. 0. 0. 1.]

**Error** 
Traceback (most recent call last):
 File "<stdin>", line 2, in <module>
 File "/home/ubuntu/kmpm/ANTsPyNet/antspynet/utilities/regression_match_image.py", line 50, in regression_match_image
  source_intensities = np.expand_dims((source_image.numpy()).flatten(), axis=1)
 File "/usr/local/lib/python3.6/dist-packages/antspyx-0.2.5-py3.6-linux-x86_64.egg/ants/core/ants_image.py", line 249, in numpy
  array = np.array(self.view(single_components=single_components), copy=True, dtype=self.dtype)
 File "/usr/local/lib/python3.6/dist-packages/antspyx-0.2.5-py3.6-linux-x86_64.egg/ants/core/ants_image.py", line 232, in view
  return np.asarray(memview).view(dtype = dtype).reshape(shape).view(np.ndarray).T
ValueError: cannot reshape array of size 12915091243008 into shape (192,192,3)

**Comment by ntustison** [comment]
The function doesn't accommodate RGB images.  Try splitting the components and perform on each channel separately.
