### ISSUE TITLE
Tensorflow version?

### ISSUE THREAD

**Issue by vsaase** [ANTsX/ANTsPyNet#3]
Hi, when trying to run BrainSegmentation with a fresh install of ANTsPyNet i get this error:

`RuntimeError: It looks like you are trying to use a version of multi-backend Keras that does not support TensorFlow 2.0. We recommend using `tf.keras`, or alternatively, downgrading to TensorFlow 1.14.`

When setting tensorflow==1.14 in setup.py I run into a different error with BrainSegmentation:

`Loading weights file
Traceback (most recent call last):
  File "Scripts/doBrainTissueSegmentation.py", line 60, in <module>
    unet_model.load_weights(weights_file_name)
  File "/Users/vsaase/anaconda3/lib/python3.7/site-packages/Keras-2.2.5-py3.7.egg/keras/engine/saving.py", line 458, in load_wrapper
    return load_function(*args, **kwargs)
  File "/Users/vsaase/anaconda3/lib/python3.7/site-packages/Keras-2.2.5-py3.7.egg/keras/engine/network.py", line 1217, in load_weights
    f, self.layers, reshape=reshape)
  File "/Users/vsaase/anaconda3/lib/python3.7/site-packages/Keras-2.2.5-py3.7.egg/keras/engine/saving.py", line 1186, in load_weights_from_hdf5_group
    reshape=reshape)
  File "/Users/vsaase/anaconda3/lib/python3.7/site-packages/Keras-2.2.5-py3.7.egg/keras/engine/saving.py", line 942, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "/Users/vsaase/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 639, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/Users/vsaase/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array
`

which Tensorflow, Numpy and Keras versions are you using? 
I am on macos 14.14 running in a fresh anaconda virtualenv with python 3.7
 also installed antspyx-0.1.8-cp37-cp37m-macosx_10_14_x86_64.whl and tensorflow_probability

thanks,
Victor

**Comment by ntustison** [comment]
Mac 14.6

Python 3.6.9

Keras                         2.2.5    
numpy                         1.17.0   
tensorflow                    1.14.0

**Comment by vnckppl** [comment]
Are these still the recommended software versions? When I install specifically these versions with pip and run ants.brain_extraction, I receive the following error:

```Using TensorFlow backend.
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "doBrainExtraction.py", line 13, in <module>
    import antspynet
  File "/usr/local/lib/python3.6/dist-packages/antspynet-0.0-py3.6.egg/antspynet/__init__.py", line 7, in <module>
    from .architectures import *
  File "/usr/local/lib/python3.6/dist-packages/antspynet-0.0-py3.6.egg/antspynet/architectures/__init__.py", line 8, in <module>
    from .create_simple_classification_with_spatial_transformer_network_model import create_simple_classification_with_spatial_transformer_network_model_2d, create_simple_classification_with_spatial_transformer_network_model_3d
  File "/usr/local/lib/python3.6/dist-packages/antspynet-0.0-py3.6.egg/antspynet/architectures/create_simple_classification_with_spatial_transformer_network_model.py", line 7, in <module>
    from ..utilities import (SpatialTransformer2D, SpatialTransformer3D)
  File "/usr/local/lib/python3.6/dist-packages/antspynet-0.0-py3.6.egg/antspynet/utilities/__init__.py", line 18, in <module>
    from .mixture_density_utilities import MixtureDensityLayer
  File "/usr/local/lib/python3.6/dist-packages/antspynet-0.0-py3.6.egg/antspynet/utilities/mixture_density_utilities.py", line 9, in <module>
    import tensorflow_probability as tfp
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_probability-0.10.0rc0-py3.6.egg/tensorflow_probability/__init__.py", line 69, in <module>
    _ensure_tf_install()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_probability-0.10.0rc0-py3.6.egg/tensorflow_probability/__init__.py", line 66, in _ensure_tf_install
    present=tf.__version__))
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.2; Detected an installation of version 1.14.0. Please upgrade TensorFlow to proceed.```

When I install the most recent version of tensorflow via pip, I receive the error that I need tensorflow > 2.2.x (the pip version is 2.1.0). When I install tensorflow nightly there are other errors.

Would it be possible to add a requirements file for ANTsPyNet to your repo?

**Comment by ntustison** [comment]
[Here](https://github.com/ANTsX/ANTsPyNet/blob/master/requirements.txt) is the requirements file.  Please feel free make a pull request to modify it such that it is up to date.  @stnava and I (and others) get stretched a bit thin trying to maintaining the various repos within the ANTsX ecosystem so any help would be much appreciated.  In particular, the python repositories (ANTsPy and ANTsPyNet) tend to be relatively more neglected because of our relative lack of proficiency.

**Comment by ntustison** [comment]
I should also mention that we really appreciate that this repo is getting used.  We actually do most of our development in ANTsRNet but we definitely want ANTs to be a part of the python community.

**Comment by vnckppl** [comment]
Hi Nick! I working on a BIDS app and decided to use ANTsPy instead of the shell scrips that I have enjoyed using for years. It would be great if I could get everything to work with Python, but if that is not feasible I would surely consider converting the project to R. 

Thanks for posting the requirements file. What I was hoping for is a list of modules and their version numbers. I am assuming that you have a working version of ANTsPyNet and was hoping to get a list of the specific versions of modules that together support a working ANTsPyNet installation. 

Currently, I have a Docker image with Ubuntu as the base setup for ANTsPy + ANTsPyNet. It has the following modules installed:
```
absl-py==0.9.0
antspynet==0.0
antspyx==0.2.5
asn1crypto==0.24.0
astor==0.8.1
backcall==0.1.0
certifi==2020.4.5.1
chardet==3.0.4
chart-studio==1.1.0
ci-info==0.2.0
click==7.1.1
cloudpickle==1.3.0
cryptography==2.1.4
cycler==0.10.0
decorator==4.4.2
etelemetry==0.2.1
filelock==3.0.12
gast==0.3.3
google-pasta==0.2.0
grpcio==1.28.1
h5py==2.10.0
idna==2.9
imageio==2.8.0
ipython==7.13.0
ipython-genutils==0.2.0
isodate==0.6.0
jedi==0.17.0
joblib==0.14.1
**Keras==2.2.5**
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keyring==10.6.0
keyrings.alt==3.0
kiwisolver==1.2.0
lxml==4.5.0
Markdown==3.2.1
matplotlib==3.2.1
networkx==2.4
neurdflib==5.0.1
nibabel==3.1.0
nilearn==0.6.2
nipype==1.4.2
**numpy==1.17.0**
packaging==20.3
pandas==1.0.3
parso==0.7.0
patsy==0.5.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.1.2
plotly==4.6.0
prompt-toolkit==3.0.5
protobuf==3.11.3
prov==1.5.3
ptyprocess==0.6.0
pycrypto==2.6.1
pydot==1.4.1
pydotplus==2.0.2
Pygments==2.6.1
pygobject==3.26.1
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
pyxdg==0.25
PyYAML==5.3.1
rdflib==5.0.0
requests==2.23.0
retrying==1.3.3
scikit-image==0.16.2
scikit-learn==0.22.2.post1
scipy==1.4.1
SecretStorage==2.3.1
simplejson==3.17.0
six==1.14.0
sklearn==0.0
statsmodels==0.11.1
svgutils==0.3.1
tensorboard==1.14.0
**tensorflow==1.14.0**
tensorflow-estimator==1.14.0
tensorflow-probability==0.10.0rc0
termcolor==1.1.0
traitlets==4.3.3
traits==6.0.0
urllib3==1.25.9
wcwidth==0.1.9
webcolors==1.11.1
Werkzeug==1.0.1
wrapt==1.12.1
```
 As you can see, I specifically installed the versions of numpy, Keras, and tensorflow that you mentioned in your previous post. Because ants.brain_extraction is still giving me errors, I was wondering if you could share your requirements for ANTsPyNet to further mimic you setup and hopefully get this to work. Thanks!!

**Comment by ntustison** [comment]
Okay, that makes sense.  Sometime after the original response above we switched to tensorflow2 so it's obviously outdated.  Here's the current list of modules:

```
% pip freeze
absl-py==0.9.0
alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.12
anaconda-project==0.8.3
ants==0.0.7
antspynet==0.0
antspyx==0.2.5
applaunchservices==0.2.1
appnope==0.1.0
appscript==1.0.1
argh==0.26.2
asgiref==3.2.7
asn1crypto==1.3.0
astroid==2.3.3
astropy==4.0
astunparse==1.6.3
atomicwrites==1.3.0
attrs==19.3.0
autopep8==1.4.4
Babel==2.8.0
backcall==0.1.0
backports.functools-lru-cache==1.6.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
beautifulsoup4==4.8.2
bitarray==1.2.1
bkcharts==0.2
bleach==3.1.0
bokeh==1.4.0
boto==2.49.0
Bottleneck==1.3.2
cachetools==4.1.0
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
chart-studio==1.1.0
Click==7.0
cloudpickle==1.3.0
clyent==1.2.2
colorama==0.4.3
conda==4.8.3
conda-build==3.18.11
conda-package-handling==1.6.0
conda-verify==3.4.2
contextlib2==0.6.0.post1
cryptography==2.8
cycler==0.10.0
Cython==0.29.15
cytoolz==0.10.1
dask==2.11.0
decorator==4.4.1
defusedxml==0.6.0
diff-match-patch==20181111
distributed==2.11.0
Django==3.0.5
docutils==0.16
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
filelock==3.0.12
flake8==3.7.9
Flask==1.1.1
fsspec==0.6.2
future==0.18.2
gast==0.3.3
gevent==1.4.0
glob2==0.7
gmpy2==2.0.8
google-auth==1.13.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
greenlet==0.4.15
grpcio==1.28.1
h5py==2.10.0
HeapDict==1.0.1
html5lib==1.0.1
hypothesis==5.5.4
idna==2.8
imageio==2.6.1
imagesize==1.2.0
importlib-metadata==1.5.0
intervaltree==3.0.2
ipykernel==5.1.4
ipython==7.12.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.14.1
Jinja2==2.11.1
joblib==0.14.1
json5==0.9.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.1.0
jupyter-core==4.6.1
jupyterlab==1.2.6
jupyterlab-server==1.0.6
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keyring==21.1.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.3
libarchive-c==2.8
lief==0.9.0
llvmlite==0.31.0
locket==0.2.0
lxml==4.5.0
Markdown==3.2.1
MarkupSafe==1.1.1
matplotlib==3.1.3
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
mock==4.0.1
more-itertools==8.2.0
mpmath==1.1.0
msgpack==0.6.1
multipledispatch==0.6.0
navigator-updater==0.2.1
nbconvert==5.6.1
nbformat==5.0.4
networkx==2.4
nibabel==3.0.2
nltk==3.4.5
nose==1.3.7
notebook==6.0.3
numba==0.48.0
numexpr==2.7.1
numpy==1.18.1
numpydoc==0.9.2
oauthlib==3.1.0
olefile==0.46
openpyxl==3.0.3
opt-einsum==3.2.0
packaging==20.1
pandas==1.0.1
pandocfilters==1.4.2
parso==0.5.2
partd==1.1.0
path==13.1.0
pathlib2==2.3.5
pathtools==0.1.2
patsy==0.5.1
pep8==1.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.0.0
pkginfo==1.5.0.1
plotly==4.6.0
pluggy==0.13.1
ply==3.11
prometheus-client==0.7.1
prompt-toolkit==3.0.3
protobuf==3.11.3
psutil==5.6.7
ptyprocess==0.6.0
py==1.8.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pycurl==7.43.0.5
pydocstyle==4.0.1
pyflakes==2.1.1
Pygments==2.5.2
pylint==2.4.4
pyodbc===4.0.0-unsupported
pyOpenSSL==19.1.0
pyparsing==2.4.6
pyrsistent==0.15.7
PySocks==1.7.1
pytest==5.3.5
pytest-arraydiff==0.3
pytest-astropy==0.8.0
pytest-astropy-header==0.1.2
pytest-doctestplus==0.5.0
pytest-openfiles==0.4.0
pytest-remotedata==0.3.2
python-dateutil==2.8.1
python-jsonrpc-server==0.3.4
python-language-server==0.31.7
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.3
pyzmq==18.1.1
QDarkStyle==2.8
QtAwesome==0.6.1
qtconsole==4.6.0
QtPy==1.9.0
requests==2.22.0
requests-oauthlib==1.3.0
retrying==1.3.3
rope==0.16.0
rsa==4.0
Rtree==0.9.3
ruamel-yaml==0.15.87
scikit-image==0.16.2
scikit-learn==0.22.1
scipy==1.4.1
seaborn==0.10.0
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.14.0
sklearn==0.0
snowballstemmer==2.0.0
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==1.9.5
Sphinx==2.4.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.2.0
spyder==4.0.1
spyder-kernels==1.8.1
SQLAlchemy==1.3.13
sqlparse==0.3.1
statsmodels==0.11.0
sympy==1.5.1
tables==3.6.1
tblib==1.6.0
tensorboard==2.2.0
tensorboard-plugin-wit==1.6.0.post3
tensorflow==2.2.0rc2
tensorflow-estimator==2.2.0rc0
tensorflow-probability==0.9.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
tfp-nightly==0.2.0.dev20200411
toolz==0.10.0
torch==1.5.0
torchvision==0.6.0a0+82fd1c8
tornado==6.0.3
tqdm==4.42.1
traitlets==4.3.3
ujson==1.35
unicodecsv==0.14.1
urllib3==1.25.8
watchdog==0.10.2
wcwidth==0.1.8
webcolors==1.11.1
webencodings==0.5.1
Werkzeug==1.0.0
widgetsnbextension==3.5.1
wrapt==1.11.2
wurlitzer==2.0.0
xlrd==1.2.0
XlsxWriter==1.2.7
xlwings==0.17.1
xlwt==1.3.0
xmltodict==0.12.0
yapf==0.28.0
zict==1.0.0
zipp==2.2.0
```
