### ISSUE TITLE
OOM error when I use brain_extraction function with 't1nobrainer'

### ISSUE THREAD

**Issue by XiDeng** [ANTsX/ANTsPyNet#44]
I run barin_extraction like this:
`t1_ex = antspynet.brain_extraction(t1_reg,'t1nobrainer',verbose=True)
`

The python log:
```
NoBrainer:  generating network.
2021-12-21 15:23:34.965128: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2d:00.0/numa_node
Your kernel may have been built without NUMA support.
2021-12-21 15:23:34.989577: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2d:00.0/numa_node
Your kernel may have been built without NUMA support.
2021-12-21 15:23:34.989966: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2d:00.0/numa_node
Your kernel may have been built without NUMA support.
2021-12-21 15:23:34.990387: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-12-21 15:23:34.991601: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2d:00.0/numa_node
Your kernel may have been built without NUMA support.
2021-12-21 15:23:34.991892: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2d:00.0/numa_node
Your kernel may have been built without NUMA support.
2021-12-21 15:23:34.992223: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2d:00.0/numa_node
Your kernel may have been built without NUMA support.
2021-12-21 15:23:35.451330: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2d:00.0/numa_node
Your kernel may have been built without NUMA support.
2021-12-21 15:23:35.451710: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2d:00.0/numa_node
Your kernel may have been built without NUMA support.
2021-12-21 15:23:35.451739: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1609] Could not identify NUMA node of platform GPU id 0, defaulting to 0.  Your kernel may not have been built with NUMA support.
2021-12-21 15:23:35.452077: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2d:00.0/numa_node
Your kernel may have been built without NUMA support.
2021-12-21 15:23:35.452146: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7399 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:2d:00.0, compute capability: 8.6
NoBrainer:  preprocessing (intensity truncation and resampling).
NoBrainer:  predicting mask.
2021-12-21 15:23:37.229864: I tensorflow/stream_executor/cuda/cuda_dnn.cc:366] Loaded cuDNN version 8100
2021-12-21 15:23:37.753854: W tensorflow/stream_executor/gpu/asm_compiler.cc:111] *** WARNING *** You are using ptxas 9.1.108, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2021-12-21 15:23:37.754745: W tensorflow/stream_executor/gpu/asm_compiler.cc:230] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.6
2021-12-21 15:23:37.754768: W tensorflow/stream_executor/gpu/asm_compiler.cc:233] Used ptxas at ptxas
2021-12-21 15:23:37.754825: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] UNIMPLEMENTED: ptxas ptxas too old. Falling back to the driver to compile.
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.
2021-12-21 15:23:56.648828: W tensorflow/core/common_runtime/bfc_allocator.cc:462] Allocator (GPU_0_bfc) ran out of memory trying to allocate 4.00GiB (rounded to 4294967296)requested by op model/conv3d_transpose_2/conv3d_transpose
If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation. 
Current allocation summary follows.
Current allocation summary follows.
2021-12-21 15:23:56.648875: I tensorflow/core/common_runtime/bfc_allocator.cc:1010] BFCAllocator dump for GPU_0_bfc
2021-12-21 15:23:56.648899: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (256):  Total Chunks: 43, Chunks in use: 43. 10.8KiB allocated for chunks. 10.8KiB in use in bin. 2.1KiB client-requested in use in bin.
2021-12-21 15:23:56.648908: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (512):  Total Chunks: 5, Chunks in use: 5. 2.5KiB allocated for chunks. 2.5KiB in use in bin. 2.5KiB client-requested in use in bin.
2021-12-21 15:23:56.648922: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (1024):         Total Chunks: 5, Chunks in use: 4. 6.0KiB allocated for chunks. 5.0KiB in use in bin. 4.7KiB client-requested in use in bin.
2021-12-21 15:23:56.648937: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (2048):         Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2021-12-21 15:23:56.648951: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (4096):         Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2021-12-21 15:23:56.648965: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (8192):         Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2021-12-21 15:23:56.648979: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (16384):        Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2021-12-21 15:23:56.648993: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (32768):        Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2021-12-21 15:23:56.649008: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (65536):        Total Chunks: 2, Chunks in use: 2. 204.0KiB allocated for chunks. 204.0KiB in use in bin. 162.0KiB client-requested in use in bin.
2021-12-21 15:23:56.649022: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (131072):       Total Chunks: 3, Chunks in use: 3. 452.0KiB allocated for chunks. 452.0KiB in use in bin. 364.0KiB client-requested in use in bin.
2021-12-21 15:23:56.649037: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (262144):       Total Chunks: 4, Chunks in use: 2. 1.19MiB allocated for chunks. 594.0KiB in use in bin. 540.0KiB client-requested in use in bin.
2021-12-21 15:23:56.649051: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (524288):       Total Chunks: 3, Chunks in use: 3. 2.11MiB allocated for chunks. 2.11MiB in use in bin. 1.34MiB client-requested in use in bin.
2021-12-21 15:23:56.649068: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (1048576):      Total Chunks: 3, Chunks in use: 3. 4.43MiB allocated for chunks. 4.43MiB in use in bin. 3.80MiB client-requested in use in bin.
2021-12-21 15:23:56.649082: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (2097152):      Total Chunks: 3, Chunks in use: 3. 8.75MiB allocated for chunks. 8.75MiB in use in bin. 7.06MiB client-requested in use in bin.
2021-12-21 15:23:56.649097: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (4194304):      Total Chunks: 2, Chunks in use: 1. 10.87MiB allocated for chunks. 5.48MiB in use in bin. 5.06MiB client-requested in use in bin.
2021-12-21 15:23:56.649110: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (8388608):      Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2021-12-21 15:23:56.649124: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (16777216):     Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2021-12-21 15:23:56.649137: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (33554432):     Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2021-12-21 15:23:56.649152: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (67108864):     Total Chunks: 1, Chunks in use: 1. 64.00MiB allocated for chunks. 64.00MiB in use in bin. 64.00MiB client-requested in use in bin.
2021-12-21 15:23:56.649165: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (134217728):    Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2021-12-21 15:23:56.649180: I tensorflow/core/common_runtime/bfc_allocator.cc:1017] Bin (268435456):    Total Chunks: 4, Chunks in use: 3. 7.13GiB allocated for chunks. 6.57GiB in use in bin. 6.50GiB client-requested in use in bin.
2021-12-21 15:23:56.649194: I tensorflow/core/common_runtime/bfc_allocator.cc:1033] Bin for 4.00GiB was 256.00MiB, Chunk State: 
2021-12-21 15:23:56.649214: I tensorflow/core/common_runtime/bfc_allocator.cc:1039]   Size: 576.00MiB | Requested Size: 528.00MiB | in_use: 0 | bin_num: 20, prev:   Size: 512.00MiB | Requested Size: 512.00MiB | in_use: 1 | bin_num: -1, next:   Size: 2.00GiB | Requested Size: 2.00GiB | in_use: 1 | bin_num: -1
2021-12-21 15:23:56.649228: I tensorflow/core/common_runtime/bfc_allocator.cc:1046] Next region of size 7758413824
2021-12-21 15:23:56.649244: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117560000 of size 1280 next 1
2021-12-21 15:23:56.649257: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117560500 of size 256 next 2
2021-12-21 15:23:56.649270: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117560600 of size 256 next 3
2021-12-21 15:23:56.649282: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117560700 of size 256 next 4
2021-12-21 15:23:56.649295: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117560800 of size 256 next 5
2021-12-21 15:23:56.649308: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117560900 of size 256 next 8
2021-12-21 15:23:56.649320: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117560a00 of size 256 next 9
2021-12-21 15:23:56.649332: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117560b00 of size 256 next 10
2021-12-21 15:23:56.649345: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117560c00 of size 256 next 13
2021-12-21 15:23:56.649358: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117560d00 of size 256 next 14
2021-12-21 15:23:56.649370: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117560e00 of size 256 next 17
2021-12-21 15:23:56.649383: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117560f00 of size 256 next 18
2021-12-21 15:23:56.649395: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117561000 of size 256 next 19
2021-12-21 15:23:56.649408: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117561100 of size 256 next 20
2021-12-21 15:23:56.649420: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117561200 of size 256 next 23
2021-12-21 15:23:56.649433: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117561300 of size 256 next 24
2021-12-21 15:23:56.649445: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117561400 of size 256 next 27
2021-12-21 15:23:56.649457: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117561500 of size 256 next 6
2021-12-21 15:23:56.649470: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117561600 of size 256 next 75
2021-12-21 15:23:56.649483: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117561700 of size 512 next 26
2021-12-21 15:23:56.649496: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117561900 of size 1024 next 7
2021-12-21 15:23:56.649509: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117561d00 of size 256 next 28
2021-12-21 15:23:56.649522: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117561e00 of size 512 next 29
2021-12-21 15:23:56.649535: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117562000 of size 256 next 32
2021-12-21 15:23:56.649547: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117562100 of size 256 next 33
2021-12-21 15:23:56.649560: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117562200 of size 512 next 36
2021-12-21 15:23:56.649572: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117562400 of size 256 next 37
2021-12-21 15:23:56.649585: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117562500 of size 256 next 38
2021-12-21 15:23:56.649597: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117562600 of size 1024 next 39
2021-12-21 15:23:56.649610: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117562a00 of size 256 next 42
2021-12-21 15:23:56.649622: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117562b00 of size 256 next 43
2021-12-21 15:23:56.649635: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] Free  at 1117562c00 of size 1024 next 44
2021-12-21 15:23:56.649647: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117563000 of size 256 next 45
2021-12-21 15:23:56.649659: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117563100 of size 256 next 47
2021-12-21 15:23:56.649672: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117563200 of size 512 next 48
2021-12-21 15:23:56.649684: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117563400 of size 512 next 52
2021-12-21 15:23:56.649696: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117563600 of size 256 next 53
2021-12-21 15:23:56.649709: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117563700 of size 256 next 54
2021-12-21 15:23:56.649721: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117563800 of size 256 next 55
2021-12-21 15:23:56.649734: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117563900 of size 256 next 40
2021-12-21 15:23:56.649746: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117563a00 of size 256 next 16
2021-12-21 15:23:56.649758: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117563b00 of size 256 next 60
2021-12-21 15:23:56.649770: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117563c00 of size 256 next 61
2021-12-21 15:23:56.649783: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117563d00 of size 256 next 62
2021-12-21 15:23:56.649795: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117563e00 of size 256 next 63
2021-12-21 15:23:56.649808: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117563f00 of size 256 next 66
2021-12-21 15:23:56.649820: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117564000 of size 256 next 67
2021-12-21 15:23:56.649832: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117564100 of size 256 next 69
2021-12-21 15:23:56.649845: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117564200 of size 256 next 70
2021-12-21 15:23:56.649857: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117564300 of size 256 next 71
2021-12-21 15:23:56.649869: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117564400 of size 256 next 72
2021-12-21 15:23:56.649882: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117564500 of size 256 next 73
2021-12-21 15:23:56.649894: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117564600 of size 1792 next 74
2021-12-21 15:23:56.649907: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117564d00 of size 98304 next 12
2021-12-21 15:23:56.649919: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 111757cd00 of size 276480 next 15
2021-12-21 15:23:56.649932: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 11175c0500 of size 110592 next 68
2021-12-21 15:23:56.649945: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 11175db500 of size 151552 next 65
2021-12-21 15:23:56.649958: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117600500 of size 180224 next 22
2021-12-21 15:23:56.649972: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 111762c500 of size 1105920 next 25
2021-12-21 15:23:56.649984: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 111773a500 of size 131072 next 58
2021-12-21 15:23:56.649997: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] Free  at 111775a500 of size 311296 next 59
2021-12-21 15:23:56.650010: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 11177a6500 of size 606208 next 57
2021-12-21 15:23:56.650023: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 111783a500 of size 720896 next 31
2021-12-21 15:23:56.650035: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 11178ea500 of size 884736 next 30
2021-12-21 15:23:56.650048: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] Free  at 11179c2500 of size 331776 next 64
2021-12-21 15:23:56.650065: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117a13500 of size 3207168 next 34
2021-12-21 15:23:56.650078: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117d22500 of size 1769472 next 51
2021-12-21 15:23:56.650091: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1117ed2500 of size 2424832 next 46
2021-12-21 15:23:56.650104: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1118122500 of size 1769472 next 49
2021-12-21 15:23:56.650116: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 11182d2500 of size 331776 next 41
2021-12-21 15:23:56.650121: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] Free  at 1118323500 of size 5648384 next 56
2021-12-21 15:23:56.650132: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1118886500 of size 3538944 next 35
2021-12-21 15:23:56.650145: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1118be6500 of size 5750784 next 50
2021-12-21 15:23:56.650158: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1119162500 of size 67108864 next 21
2021-12-21 15:23:56.650171: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 111d162500 of size 536870912 next 79
2021-12-21 15:23:56.650184: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] Free  at 113d162500 of size 603979776 next 76
2021-12-21 15:23:56.650196: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 1161162500 of size 2147483648 next 77
2021-12-21 15:23:56.650210: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] InUse at 11e1162500 of size 4373601024 next 18446744073709551615
2021-12-21 15:23:56.650222: I tensorflow/core/common_runtime/bfc_allocator.cc:1071]      Summary of in-use Chunks by size: 
2021-12-21 15:23:56.650236: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 43 Chunks of size 256 totalling 10.8KiB
2021-12-21 15:23:56.650250: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 5 Chunks of size 512 totalling 2.5KiB
2021-12-21 15:23:56.650264: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 2 Chunks of size 1024 totalling 2.0KiB
2021-12-21 15:23:56.650277: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 1280 totalling 1.2KiB
2021-12-21 15:23:56.650290: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 1792 totalling 1.8KiB
2021-12-21 15:23:56.650304: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 98304 totalling 96.0KiB
2021-12-21 15:23:56.650317: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 110592 totalling 108.0KiB
2021-12-21 15:23:56.650330: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 131072 totalling 128.0KiB
2021-12-21 15:23:56.650344: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 151552 totalling 148.0KiB
2021-12-21 15:23:56.650357: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 180224 totalling 176.0KiB
2021-12-21 15:23:56.650370: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 276480 totalling 270.0KiB
2021-12-21 15:23:56.650384: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 331776 totalling 324.0KiB
2021-12-21 15:23:56.650397: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 606208 totalling 592.0KiB
2021-12-21 15:23:56.650411: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 720896 totalling 704.0KiB
2021-12-21 15:23:56.650424: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 884736 totalling 864.0KiB
2021-12-21 15:23:56.650437: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 1105920 totalling 1.05MiB
2021-12-21 15:23:56.650450: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 2 Chunks of size 1769472 totalling 3.38MiB
2021-12-21 15:23:56.650463: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 2424832 totalling 2.31MiB
2021-12-21 15:23:56.650468: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 3207168 totalling 3.06MiB
2021-12-21 15:23:56.650471: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 3538944 totalling 3.38MiB
2021-12-21 15:23:56.650475: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 5750784 totalling 5.48MiB
2021-12-21 15:23:56.650486: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 67108864 totalling 64.00MiB
2021-12-21 15:23:56.650500: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 536870912 totalling 512.00MiB
2021-12-21 15:23:56.650513: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 2147483648 totalling 2.00GiB
2021-12-21 15:23:56.650526: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] 1 Chunks of size 4373601024 totalling 4.07GiB
2021-12-21 15:23:56.650539: I tensorflow/core/common_runtime/bfc_allocator.cc:1078] Sum Total of in-use chunks: 6.66GiB
2021-12-21 15:23:56.650552: I tensorflow/core/common_runtime/bfc_allocator.cc:1080] total_region_allocated_bytes_: 7758413824 memory_limit_: 7758413824 available bytes: 0 curr_region_allocation_bytes_: 15516827648
2021-12-21 15:23:56.650568: I tensorflow/core/common_runtime/bfc_allocator.cc:1086] Stats: 
Limit:                      7758413824
InUse:                      7148141568
MaxInUse:                   7148141568
NumAllocs:                         249
MaxAllocSize:               4373601024
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2021-12-21 15:23:56.650585: W tensorflow/core/common_runtime/bfc_allocator.cc:474] *********______************************************************************************************x
2021-12-21 15:23:56.650632: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_grad_ops_3d.cc:1471 : RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[1,64,256,256,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/mnt/c/Users/***/Desktop/QSM/3DT1/seg.py", line 8, in <module>
    t1_ex = antspynet.brain_extraction(t1_reg,'t1nobrainer',verbose=True)
  File "/home/***/.local/lib/python3.8/site-packages/antspynet/utilities/brain_extraction.py", line 225, in brain_extraction
    brain_mask_array = np.squeeze(model.predict(image_array, verbose=verbose))
  File "/home/***/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/***/.local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 58, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[1,64,256,256,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node model/conv3d_transpose_2/conv3d_transpose
 (defined at /home/***/.local/lib/python3.8/site-packages/keras/layers/convolutional.py:1646)
]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__inference_predict_function_864]

Errors may have originated from an input operation.
Input Source operations connected to node model/conv3d_transpose_2/conv3d_transpose:
In[0] model/conv3d_transpose_2/stack (defined at /home/***/.local/lib/python3.8/site-packages/keras/layers/convolutional.py:1645)
In[1] model/conv3d_transpose_2/conv3d_transpose/ReadVariableOp:
In[2] model/re_lu_11/Relu (defined at /home/***/.local/lib/python3.8/site-packages/keras/backend.py:4867)

Operation defined at: (most recent call last)
>>>   File "/mnt/c/Users/***/Desktop/QSM/3DT1/seg.py", line 8, in <module>
>>>     t1_ex = antspynet.brain_extraction(t1_reg,'t1nobrainer',verbose=True)
>>> 
>>>   File "/home/***/.local/lib/python3.8/site-packages/antspynet/utilities/brain_extraction.py", line 225, in brain_extraction
>>>     brain_mask_array = np.squeeze(model.predict(image_array, verbose=verbose))
>>> 
>>>   File "/home/***/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/home/***/.local/lib/python3.8/site-packages/keras/engine/training.py", line 1789, in predict
>>>     tmp_batch_outputs = self.predict_function(iterator)
>>> 
>>>   File "/home/***/.local/lib/python3.8/site-packages/keras/engine/training.py", line 1621, in predict_function
>>>     return step_function(self, iterator)
>>> 
>>>   File "/home/***/.local/lib/python3.8/site-packages/keras/engine/training.py", line 1611, in step_function
>>>     outputs = model.distribute_strategy.run(run_step, args=(data,))
>>> 
>>>   File "/home/***/.local/lib/python3.8/site-packages/keras/engine/training.py", line 1604, in run_step
>>>     outputs = model.predict_step(data)
>>> 
>>>   File "/home/***/.local/lib/python3.8/site-packages/keras/engine/training.py", line 1572, in predict_step
>>>     return self(x, training=False)
>>> 
>>>   File "/home/***/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/home/***/.local/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/home/***/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/home/***/.local/lib/python3.8/site-packages/keras/engine/functional.py", line 451, in call
>>>     return self._run_internal_graph(
>>> 
>>>   File "/home/***/.local/lib/python3.8/site-packages/keras/engine/functional.py", line 589, in _run_internal_graph
>>>     outputs = node.layer(*args, **kwargs)
>>> 
>>>   File "/home/***/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/home/***/.local/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/home/***/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/home/***/.local/lib/python3.8/site-packages/keras/layers/convolutional.py", line 1646, in call
>>>     outputs = tf.nn.conv3d_transpose(
>>> 
```

I don't know what happen and how to solve this problem.
Thank you for your helps.

**Comment by ntustison** [comment]
The "nobrainer" option has a heavy memory footprint which is why I typically don't run it on the GPU.  What happens when you try to run it through the CPU?

**Comment by XiDeng** [comment]
> The "nobrainer" option has a heavy memory footprint which is why I typically don't run it on the GPU. What happens when you try to run it through the CPU?

How can I run it through the CPU? It seems the function runs on the GPU automatically. 😂

**Comment by ntustison** [comment]
This is a generic usage question the is prior to using ANTsPyNet.  Try looking online.  My guess would be to start with the ``CUDA_VISIBLE_DEVICES`` environmental variable.

**Comment by XiDeng** [comment]
Yep. I ran these two lines of code before extracting:
```
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"  
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
```
and the function runs on the CPU successfully.

Thank you so much!
