### ISSUE TITLE
antspyx version

### ISSUE THREAD

**Issue by scalphunters** [ANTsX/ANTsPyNet#62]
Thanks for the great work. I recently found out the antspyx changed its build engine to more recent version of cmake and it fails to build even though I tried with older version of antspynet.

Since setup.py has no version specified for some libraries (antspyx), the build fails due to changed version of cmake for antspyx's new version. Can this be fixed? Although I can fork the repo to be used for my application, it would be bit cumbersome to integrate antspynet as a part of the software.

Can you specify the version of antspyx in requirements.txt as well as other libs like keras?

Thanks again and have a good day

**Comment by ntustison** [comment]
I just use the latest pull from the antspy repository.  I would recommend trying that.

**Comment by scalphunters** [comment]
The depending library of antspynet changed its version of cmake. So only feasible way to overcome this is to upgrade cmake.  Thanks for your help. I'll close the issue.

# Below is the error message in both cases (older version, latest release).

You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.
    
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:
    
      git checkout -b new_branch_name
    
    HEAD is now at fc16efb... Merge pull request #1317 from ANTsX/hdf5TransformWrite
    Configuring ANTsPy library
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zddikisv/antspyx/setup.py", line 177, in <module>
        setup(
      File "/Zylka/DTI/tests-tools/env/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/NIRAL/tools/devel/linux/Python/Python-3.8.6/Lib/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/NIRAL/tools/devel/linux/Python/Python-3.8.6/Lib/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/NIRAL/tools/devel/linux/Python/Python-3.8.6/Lib/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-zddikisv/antspyx/setup.py", line 55, in run
        self.run_command("build_py")
      File "/NIRAL/tools/devel/linux/Python/Python-3.8.6/Lib/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/NIRAL/tools/devel/linux/Python/Python-3.8.6/Lib/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-zddikisv/antspyx/setup.py", line 40, in run
        self.run_command("build_ext")
      File "/NIRAL/tools/devel/linux/Python/Python-3.8.6/Lib/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/NIRAL/tools/devel/linux/Python/Python-3.8.6/Lib/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-zddikisv/antspyx/setup.py", line 113, in run
        raise RuntimeError("CMake >= 3.10.0 is required")
    RuntimeError: CMake >= 3.10.0 is required
